service: sls-typescript-boiler

useDotenv: true

custom:
  serverless-offline:
    noAuth: true
    host: 0.0.0.0

plugins:
  - serverless-prune-plugin
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
      - http:
          path: /{any+}
          method: ANY
          cors:
            origin: '*'

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
